<?php

App::import('Sanitize');

class EmployeesController extends HrAppController {

    var $name = 'Employees';

    function index() {
        $locations = $this->Employee->EmpLoc->find('all');
        $this->set(compact('locations'));
    }

    function index6() {
        $locations = $this->Employee->EmpLoc->find('all');
        $this->set(compact('locations'));
    }

    function index5() {
        $locations = $this->Employee->EmpLoc->find('all');
        $this->set(compact('locations'));
    }

    function index3() {
        $locations = $this->Employee->EmpLoc->find('all');
        $this->set(compact('locations'));
    }

    function index4() {
        $locations = $this->Employee->EmpLoc->find('all');
        $this->set(compact('locations'));
    }

    function index2($id = null) {
        $this->set('parent_id', $id);
    }

    function search() {
        
    }

    function sendsmsusers() {
        $this->autoRender = false;
        $this->Employee->recursive = 2;
        $emps = $this->Employee->find('all', array('conditions' => array('status' => 'active')));
        //print_r($emps);
        foreach ($emps as $emp) {
            if ($emp['Employee']['telephone'] !== '') {
                if (!empty($emp['User']) && !empty($emp['User']['Person'])) {
                    $number = trim($emp['Employee']['telephone']);
                    $text = "Hello " . $emp['User']['Person']['first_name'] . ", Your EthioHR account is   U:" . $emp['User']['username'] . " P:123456  Go to http://www.ethiohr.com.et/web-portal to login. Thanks.";
                    echo $text;
                    $this->data['TextMessage']['name'] = $number;
                    $this->data['TextMessage']['text'] = $text;
                    $this->loadModel('TextMessage');
                    $this->TextMessage->create();
                    $this->TextMessage->save($this->data);
                }
            }
        }
    }

    function sendusers() {
        $this->autoRender = false;
        $this->Employee->recursive = 2;
        $emps = $this->Employee->find('all', array('conditions' => array('status' => 'active')));
        foreach ($emps as $emp) {
            if (!empty($emp['User']) && !empty($emp['User']['email']) && !empty($emp['User']['Person'])) {
                $fullname = $emp['User']['Person']['first_name'] . ' ' . $emp['User']['Person']['middle_name'];
                $username = $emp['User']['username'] . '<br>';
                $password = '123456';
                $from = 'ethio_hr@ethiohr.com.et';
                $from_name = 'EthioHR';
                $subject = "Your EthioHR System Account";
                //echo $body;
                $body = '<table width="502" border="0">
  <tr>
    <td width="492" height="46" align="right" bgcolor="#0066FF" color="#fff"><div align="center" style="color:#fff"><span>Welcome to EthioHR System</span></div></td>
  </tr>
  <tr>
    <td  style="font-family: Arial,Helvetica,sans-serif;font-size: 14px;"><p>To:  ' . $fullname . '</p>      <p class="style7">&nbsp;&nbsp;&nbsp;Your EthioHR System Account is:<br />
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User Name: <strong>' . $username . '</strong><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Password: <strong>' . $password . '</strong><br />
        <br />
&nbsp;
&nbsp;&nbsp;Use the address <strong>http://www.ethiohr.com.et/web-portal</strong> to access your account and Please change your password after first login!<br />
        <br />
&nbsp;&nbsp;Regards,<br />
&nbsp;&nbsp;EthioHR</p><hr></td>
  </tr>
  <tr>
    <td><span style="color:#999;font-size: 12px;">* Note: Please don\'t reply to this address, it is generated by the system.</span></td>
  </tr>
</table>';
                $this->data['Email']['name'] = $subject;
                $this->data['Email']['to'] = $emp['User']['email'];
                $this->data['Email']['from'] = $from;
                $this->data['Email']['from_name'] = $from_name;
                $this->data['Email']['body'] = $body;
                $this->loadModel('Email');
                $this->Email->create();
                $this->Email->save($this->data);
                echo $body;
                // $this->smtpmailer($to, $from, $from_name, $subject, $body, false);
            }
        }
    }

    function message($id = null) {
        if (!empty($this->data)) {
            $from = 'ethio_hr@ethiohr.com.et';
            $from_name = 'EthioHR';
            $subject = $this->data['Employee']['subject'];
            $body = $this->data['Employee']['message'];

            $conditions['Employee.status'] = 'active';
            //$conditions['Employee.id']='2';
            $this->Employee->recursive = 2;
            $employees = $this->Employee->find('all', array('conditions' => $conditions));
            //print_r($employees);
            foreach ($employees as $employee) {
                if ($this->data['Employee']['use'] == 'SMS' || $this->data['Employee']['use'] == 'Both') {
                    $tel = $employee['Employee']['telephone'];
                    $this->data['TextMessage']['name'] = $tel;
                    $this->data['TextMessage']['text'] = $body;
                    $this->loadModel('TextMessage');
                    $this->TextMessage->create();
                    $this->TextMessage->save($this->data);
                }
                if ($this->data['Employee']['use'] == 'Email' || $this->data['Employee']['use'] == 'Both') {
                    if (!empty($employee['User'])) {
                        $this->data['Email']['name'] = $subject;
                        $this->data['Email']['to'] = $employee['User']['email'];
                        $this->data['Email']['from'] = $from;
                        $this->data['Email']['from_name'] = $from_name;
                        $this->data['Email']['body'] = $body;
                        $this->loadModel('Email');
                        $this->Email->create();
                        $this->Email->save($this->data);
                        $to = $employee['User']['email'];
                        //$this->smtpmailer($to, $from, $from_name, $subject, $body, false);
                    }
                }
            }
            $this->Session->setFlash(__('Message Sent to Quie.', true), '');

            $this->render('/elements/success');
        }
        if ($id)
            $this->set('parent_id', $id);
        $employees = $this->Employee->find('list');
        $this->set(compact('employees'));
    }

    function search_emp() {
        //$this->loadModel('Person');
        $this->Employee->recursive = 2;
        //$people = $this->Person->find('list');
        $conditions['Employee.status'] = 'active';
        $this->set('people', $this->Employee->find('all', array('conditions' => $conditions)));
        //$this->set('results', $this->Person->find('count'));
    }

    function search_emp6() {
        //$this->loadModel('Person');
        $this->Employee->recursive = 2;
        //$people = $this->Person->find('list');
        $conditions['Employee.status'] = 'deactivated';
        $this->set('people', $this->Employee->find('all', array('conditions' => $conditions)));
        //$this->set('results', $this->Person->find('count'));
    }

    function array_sort_by_column(&$arr, $col, $dir = SORT_ASC) {
        $sort_col = array();
        foreach ($arr as $key => $row) {
            $sort_col[$key] = $row[$col];
        }

        array_multisort($sort_col, $dir, $arr);
    }

    function scale_up_all() {
        $this->autoRender = false;
        $this->Employee->recursive = 2;
        $employees = $this->Employee->find('all');
        //print_r($employees);
        foreach ($employees as $employee) {
            if (!empty($employee['EmployeeDetail'])) {
                // print_r($employee);
                $datestart = $employee['EmployeeDetail'];
                $this->array_sort_by_column($datestart, "start_date");
                if ($datestart[0]['start_date'] < "2013-01-04") {//leave out employees not stayed for six month
                    $this->datax['EmployeeDetail']['end_date'] = '2013-06-30';
                    if (count($employee['EmployeeDetail']) > 1)
                        $this->array_sort_by_column($employee['EmployeeDetail'], "start_date", SORT_DESC);
                    $this->datax['EmployeeDetail']['id'] = $employee['EmployeeDetail'][0]['id'];
                    $this->loadModel('EmployeeDetail');
                    $this->EmployeeDetail->save($this->datax);
                    //print_r($this->datax);
                    $con['Scale.grade_id'] = $employee['EmployeeDetail'][0]['grade_id'];
                    $con['Scale.step_id'] = '2';
                    $this->loadModel('Scale');
                    $salary = $this->Scale->find('all', array('conditions' => $con));
                    $this->data['EmployeeDetail']['salary'] = $salary[0]['Scale']['salary'];

                    $this->data['EmployeeDetail']['step_id'] = '2';
                    $this->data['EmployeeDetail']['start_date'] = '2013-07-01';
                    $this->data['EmployeeDetail']['employee_id'] = $employee['EmployeeDetail'][0]['employee_id'];
                    $this->data['EmployeeDetail']['grade_id'] = $employee['EmployeeDetail'][0]['grade_id'];
                    $this->data['EmployeeDetail']['position_id'] = $employee['EmployeeDetail'][0]['position_id'];

                    $this->loadModel('EmployeeDetail');
                    $this->EmployeeDetail->create();
                    //$this->data['EmployeeDetail']['id']=null;
                    $this->data['EmployeeDetail']['end_date'] = '';
                    $this->EmployeeDetail->save($this->data);
                    //echo $employee['User']['Person']['first_name'].'|'.$employee['EmployeeDetail'][0]['Position']['name'].'<br>';
                    // print_r($this->data);
                }
            }
        }
    }

    function clear_data() {
        $this->autoRender = false;
        $this->Employee->recursive = 2;
        $employees = $this->Employee->find('all');
        //print_r($employees);
        foreach ($employees as $employee) {
            if (empty($employee['User']['id'])) {
                //print_r($employee);
                $this->Employee->delete($employee['Employee']['id']);
            } else if (empty($employee['User']['Person'])) {
                //print_r($employee);
                $this->Employee->delete($employee['Employee']['id']);
            } else if (empty($employee['EmployeeDetail'])) {
                print_r($employee);
                // $this->Employee->delete($employee['Employee']['id']);
            } else if ($employee['Employee']['status'] == 'deleted') {
                $this->Employee->delete($employee['Employee']['id']);
            }
        }
    }

    function list_data($id = null) {

        $start = (isset($_REQUEST['start'])) ? $_REQUEST['start'] : 0;
        $limit = (isset($_REQUEST['limit'])) ? $_REQUEST['limit'] : 20;
        $location_id = (isset($_REQUEST['location_id'])) ? $_REQUEST['location_id'] : -1;
        if ($id)
            $location_id = ($id) ? $id : -1;
        $conditions = (isset($_REQUEST['conditions'])) ? $_REQUEST['conditions'] : '';

        eval("\$conditions = array( " . $conditions . " );");
        if (isset($conditions['Employee.name LIKE'])) {
            if (trim($conditions['Employee.name LIKE']) == '%%')
                unset($conditions['Employee.name LIKE']);
        }
        if (isset($conditions['Employee.name LIKE'])) {
            $fullname = str_replace('%', '', $conditions['Employee.name LIKE']);
            unset($conditions['Employee.name LIKE']);
            $xx = explode(' ', trim($fullname));
            $con['Person.first_name LIKE'] = (isset($xx[0])) ? trim($xx[0]) . '%' : '%%';
            $con['Person.middle_name LIKE'] = (isset($xx[1])) ? trim($xx[1]) . '%' : '%%';
            $con['Person.last_name LIKE'] = (isset($xx[2])) ? trim($xx[2]) . '%' : '%%';
            //print_r($xx);
            if (count($xx) < 10) {
                //$this->Employee->User->Person->recursive=4;
                $peos = $this->Employee->User->Person->find('all', array('conditions' => $con));

                $condu = array();
                foreach ($peos as $peo) {
                    if (isset($peo['User'][0]))
                        $condu = array_merge(array($peo['User'][0]['id']), $condu);
                }
            }else
                $condu = array('-1');
            $conditions = array_merge(array("OR" => array("Employee.user_id" => $condu)), $conditions);
        }
        if ($location_id != -1) {
            $conditions['Employee.location_id'] = $location_id;
        }
        $this->Employee->recursive = 2;
        $conditions['Employee.status'] = 'active';
        //'order' => 'User.username'
        $employees = $this->Employee->find('all', array('conditions' => $conditions, 'order' => 'User.username', 'limit' => $limit, 'offset' => $start));
        $this->set('employees', $employees);
        //print_r($employees);
        $this->set('results', $this->Employee->find('count', array('conditions' => $conditions)));
    }

    function list_data6($id = null) {

        $start = (isset($_REQUEST['start'])) ? $_REQUEST['start'] : 0;
        $limit = (isset($_REQUEST['limit'])) ? $_REQUEST['limit'] : 20;
        $location_id = (isset($_REQUEST['location_id'])) ? $_REQUEST['location_id'] : -1;
        if ($id)
            $location_id = ($id) ? $id : -1;
        $conditions = (isset($_REQUEST['conditions'])) ? $_REQUEST['conditions'] : '';

        eval("\$conditions = array( " . $conditions . " );");
        if (isset($conditions['Employee.name LIKE'])) {
            if (trim($conditions['Employee.name LIKE']) == '%%')
                unset($conditions['Employee.name LIKE']);
        }
        if (isset($conditions['Employee.name LIKE'])) {
            $fullname = str_replace('%', '', $conditions['Employee.name LIKE']);
            unset($conditions['Employee.name LIKE']);
            $xx = explode(' ', trim($fullname));
            $con['Person.first_name LIKE'] = (isset($xx[0])) ? trim($xx[0]) . '%' : '%%';
            $con['Person.middle_name LIKE'] = (isset($xx[1])) ? trim($xx[1]) . '%' : '%%';
            $con['Person.last_name LIKE'] = (isset($xx[2])) ? trim($xx[2]) . '%' : '%%';
            //print_r($xx);
            if (count($xx) < 10) {
                //$this->Employee->User->Person->recursive=4;
                $peos = $this->Employee->User->Person->find('all', array('conditions' => $con));

                $condu = array();
                foreach ($peos as $peo) {
                    if (isset($peo['User'][0]))
                        $condu = array_merge(array($peo['User'][0]['id']), $condu);
                }
            }else
                $condu = array('-1');
            $conditions = array_merge(array("OR" => array("Employee.user_id" => $condu)), $conditions);
        }
        if ($location_id != -1) {
            $conditions['Employee.location_id'] = $location_id;
        }
        $this->Employee->recursive = 2;
        $conditions['Employee.status'] = 'deactivated';
        //'order' => 'User.username'
        $employees = $this->Employee->find('all', array('conditions' => $conditions, 'order' => 'User.username', 'limit' => $limit, 'offset' => $start));
        $this->set('employees', $employees);
        //print_r($employees);
        $this->set('results', $this->Employee->find('count', array('conditions' => $conditions)));
    }

    function list_data5($id = null) {

        $start = (isset($_REQUEST['start'])) ? $_REQUEST['start'] : 0;
        $limit = (isset($_REQUEST['limit'])) ? $_REQUEST['limit'] : 20;
        $location_id = (isset($_REQUEST['location_id'])) ? $_REQUEST['location_id'] : -1;
        if ($id)
            $location_id = ($id) ? $id : -1;
        $conditions = (isset($_REQUEST['conditions'])) ? $_REQUEST['conditions'] : '';

        eval("\$conditions = array( " . $conditions . " );");
        if (isset($conditions['Employee.name LIKE'])) {
            if (trim($conditions['Employee.name LIKE']) == '%%')
                unset($conditions['Employee.name LIKE']);
        }
        if (isset($conditions['Employee.name LIKE'])) {
            $fullname = str_replace('%', '', $conditions['Employee.name LIKE']);
            unset($conditions['Employee.name LIKE']);
            $xx = explode(' ', trim($fullname));
            $con['Person.first_name LIKE'] = (isset($xx[0])) ? trim($xx[0]) . '%' : '%%';
            $con['Person.middle_name LIKE'] = (isset($xx[1])) ? trim($xx[1]) . '%' : '%%';
            $con['Person.last_name LIKE'] = (isset($xx[2])) ? trim($xx[2]) . '%' : '%%';
            //print_r($xx);
            if (count($xx) < 10) {
                //$this->Employee->User->Person->recursive=4;
                $peos = $this->Employee->User->Person->find('all', array('conditions' => $con));

                $condu = array();
                foreach ($peos as $peo) {
                    if (isset($peo['User'][0]))
                        $condu = array_merge(array($peo['User'][0]['id']), $condu);
                }
            }else
                $condu = array('-1');
            $conditions = array_merge(array("OR" => array("Employee.user_id" => $condu)), $conditions);
        }
        if ($location_id != -1) {
            $conditions['Employee.location_id'] = $location_id;
        }
        $conditions['Employee.user_id'] = $this->Session->read('Auth.User.id');
        $this->Employee->recursive = 2;
        $employees = $this->Employee->find('all', array('conditions' => $conditions, 'order' => 'User.username', 'limit' => $limit, 'offset' => $start));
        $this->set('employees', $employees);
        //print_r($employees);
        $this->set('results', $this->Employee->find('count', array('conditions' => $conditions)));
    }

    function list_data3($id = null) {

        $start = (isset($_REQUEST['start'])) ? $_REQUEST['start'] : 0;
        $limit = (isset($_REQUEST['limit'])) ? $_REQUEST['limit'] : 200;

        $conditions['PayrollEmployee.payroll_id'] = $this->Session->read('Auth.User.payroll_id');
        $this->loadModel('PayrollEmployee');
        $this->PayrollEmployee->recursive = 3;
        $employees = $this->PayrollEmployee->find('all', array('conditions' => $conditions, 'limit' => $limit, 'offset' => $start));
        $this->set('employees', $employees);
        $this->set('results', $this->PayrollEmployee->find('count', array('conditions' => $conditions, 'limit' => $limit, 'offset' => $start)));
    }

    function list_data4($id = null) {

        $start = (isset($_REQUEST['start'])) ? $_REQUEST['start'] : 0;
        $limit = (isset($_REQUEST['limit'])) ? $_REQUEST['limit'] : 200;

        //print_r($this->Session->read('Auth.User'));
        $this->loadModel('Employee');
        $employees = array();
        $sup = $this->Employee->find('all', array('conditions' => array('user_id' => $this->Session->read('Auth.User.id'))));
        if (!empty($sup)) {
            $conditions['Supervisor.sup_emp_id'] = $sup[0]['Employee']['id'];
            $this->loadModel('Supervisor');
            $this->Supervisor->recursive = 3;
            $employees = $this->Supervisor->find('all', array('conditions' => $conditions, 'limit' => $limit, 'offset' => $start));
            //$this->set('results', $this->Supervisor->find('count', array('conditions' => $conditions, 'limit' => $limit, 'offset' => $start)));
        }
        $this->set('employees', $employees);
        $this->set('results', count($employees));
    }

    function list_city($id = null) {
        $start = (isset($_REQUEST['start'])) ? $_REQUEST['start'] : 0;
        $limit = (isset($_REQUEST['limit'])) ? $_REQUEST['limit'] : 20;
        $location_id = (isset($_REQUEST['location_id'])) ? $_REQUEST['location_id'] : -1;
        if ($id)
            $location_id = ($id) ? $id : -1;
        $conditions = (isset($_REQUEST['conditions'])) ? $_REQUEST['conditions'] : '';

        eval("\$conditions = array( " . $conditions . " );");
        if ($location_id != -1) {
            $conditions['Employee.location_id'] = $location_id;
        }
        $this->Employee->recursive = 2;
        $this->set('employees', $this->Employee->find('all', array('conditions' => $conditions, 'limit' => $limit, 'offset' => $start, 'group' => 'city')));
        $this->set('results', $this->Employee->find('count', array('conditions' => $conditions)));
    }

    function view($id = null) {
        if (!$id) {
            $this->Session->setFlash(__('Invalid employee', true));
            $this->redirect(array('action' => 'index'));
        }
        $this->Employee->recursive = 2;
        $this->set('employee', $this->Employee->read(null, $id));
    }

    function smtpmailer($to, $from, $from_name, $subject, $body, $is_gmail = true) {
        include(APPLIBS . DS . "PHPMailer" . DS . "class.phpmailer.php");
        $mail = new PHPMailer();  // create a new object
        $mail->IsSMTP(); // enable SMTP
        $mail->SMTPDebug = 1;  // debugging: 1 = errors and messages, 2 = messages only
        $mail->SMTPAuth = true;  // authentication enabled
        if ($is_gmail) {
            $mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for GMail
            $mail->Host = 'smtp.gmail.com';
            $mail->Port = 465;
            $mail->Username = 'ethio_hr@gmail.com';
            $mail->Password = 'X@43_mayl';
        }

        $mail->SetFrom($from, $from_name);
        $mail->Subject = $subject;
        $mail->Body = $body;
        $mail->AddAddress($to);
        if (!$mail->Send()) {
            return 'Mail error: ' . $mail->ErrorInfo;
        } else {
            return true;
        }
    }

    function add($id = null) {
        /*  $to      = 'abenxr@gmail.com';
          $subject = 'the subject';
          $message = 'hello';
          $headers = 'From: webmaster@example.com' . "\r\n" .
          'Reply-To: webmaster@example.com' . "\r\n" .
          'X-Mailer: PHP/' . phpversion();

          mail($to, $subject, $message); */

        App::import('Amharic');
        if (!empty($this->data)) {
            $this->data['Person']['first_name'] = Sanitize::paranoid($this->data['Person']['first_name']);
            $this->data['Person']['middle_name'] = Sanitize::paranoid($this->data['Person']['middle_name']);
            $this->data['Person']['last_name'] = Sanitize::paranoid($this->data['Person']['last_name']);

            $this->Employee->create();
            $this->autoRender = false;
            if (isset($this->data['Employee']['photo'])) {
                $this->data['Employee']['photox'] = $this->data['Employee']['photo'];
                $photox = $this->data['Employee']['photo'];
                $this->data['Employee']['photo'] = $this->data['Employee']['photo']["name"];
            }
            $this->data = Sanitize::clean($this->data);
            $this->data['Employee']['mother_name_am'] = Amharic::encode_amharic($this->data['Employee']['mother_name_am']);
            $this->data['Employee']['spouse_name_am'] = Amharic::encode_amharic($this->data['Employee']['spouse_name_am']);
            $this->data['Employee']['contact_name_am'] = Amharic::encode_amharic($this->data['Employee']['contact_name_am']);
            $date_parts = explode('/', $this->data['Employee']['date_of_employment_am']);
            $this->data['Employee']['date_of_employment'] = $this->ConvertEthiopicToGregoreanDate($date_parts[2], $date_parts[1], $date_parts[0]);
            
            $this->layout = 'message_layout';
            if ($this->Employee->save($this->data)) {
                
                $this->data['Person']['first_name_am'] = Amharic::encode_amharic($this->data['Person']['first_name_am']);
                $this->data['Person']['middle_name_am'] = Amharic::encode_amharic($this->data['Person']['middle_name_am']);
                $this->data['Person']['last_name_am'] = Amharic::encode_amharic($this->data['Person']['last_name_am']);
                
                
                $this->Employee->User->Person->create();
                $this->Employee->User->Person->save($this->data);
                $this->data['User']['person_id'] = $this->Employee->User->Person->getLastInsertId();
                $this->data['Person']['first_name'] = ereg_replace(' ', '', $this->data['Person']['first_name']);
                $this->data['Person']['first_name'] = ereg_replace("\n", '', $this->data['Person']['first_name']);
                $this->data['Person']['first_name'] = ereg_replace("\t", '', $this->data['Person']['first_name']);
                $this->data['User']['username'] = trim($this->data['Person']['first_name']) . $this->data['User']['person_id'];
                $pwd = rand(2000, 9000);
                $this->data['User']['password'] = $this->Auth->password('123456');
                $this->data['User']['is_active'] = 1;
                $this->Employee->User->create();
                $this->Employee->User->save($this->data);

                if (isset($photox)) {
                    $allowedExts = array("jpg", "jpeg", "gif", "png");
                    $extension = end(explode(".", $photox["name"]));
                    if ((($photox["type"] == "image/gif")
                            || ($photox["type"] == "image/jpeg")
                            || ($photox["type"] == "image/png")
                            || ($photox["type"] == "image/pjpeg"))
                            && in_array($extension, $allowedExts)) {
                        if ($photox["error"] > 0) {
                            
                        } else {
                            if (!is_dir(IMAGES . "employee_photos"))
                                mkdir(IMAGES . "employee_photos", 0777);

                            $photox["name"] = $this->Employee->getLastInsertId() . "." . $extension;
                            move_uploaded_file($photox["tmp_name"], IMAGES . "employee_photos" . DS . $photox["name"]);
                            $this->data['Employee']['photo'] = $photox["name"];
                            $file_name = $photox["name"];
                            $ext = substr($file_name, strripos($file_name, '.') + 1);

                            if (in_array($ext, array('png', 'jpg', 'jpeg', 'gif'))) {
                                list($w1, $h1) = getimagesize(IMAGES . 'employee_photos' . DS . $file_name);
                                if ($w1 > 150) {
                                    // Load
                                    $w2 = 150;
                                    $h2 = ($w2 * $h1) / $w1;
                                    if ($h2 > 190)
                                        $h2 = 190;

                                    $thumb = imagecreatetruecolor($w2, $h2);
                                    $source = null;
                                    if (in_array($ext, array('jpg', 'jpeg')))
                                        $source = imagecreatefromjpeg(IMAGES . 'employee_photos' . DS . $file_name);
                                    elseif (in_array($ext, array('png')))
                                        $source = imagecreatefrompng(IMAGES . 'employee_photos' . DS . $file_name);
                                    else
                                        $source = imagecreatefromgif(IMAGES . 'employee_photos' . DS . $file_name);
                                    // Resize
                                    imagecopyresized($thumb, $source, 0, 0, 0, 0, $w2, $h2, $w1, $h1);
                                    //$new_image = 'acuity_' . date('YmdHi') . '.png';
                                    if (in_array($ext, array('jpg', 'jpeg')))
                                        imagejpeg($thumb, IMAGES . 'employee_photos' . DS . $file_name);
                                    elseif (in_array($ext, array('png')))
                                        imagepng($thumb, IMAGES . 'employee_photos' . DS . $file_name);
                                    else
                                        imagegif($thumb, IMAGES . 'employee_photos' . DS . $file_name);

                                    //unlink(IMAGES . 'employee_photos' . DS . $file_name);
                                }
                            }
                        }
                    }
                }
                $this->data['EmployeeDetail']['employee_id'] = $this->Employee->getLastInsertId();
                $this->data['Employee']['user_id'] = $this->Employee->User->getLastInsertId();
                $this->Employee->save($this->data);
                $this->data['EmployeeDetail']['start_date'] = $this->data['Employee']['date_of_employment'];
                $this->data['EmployeeDetail']['end_date'] = '';
                $this->data['EmployeeDetail']['branch_id'] = $this->data['User']['branch_id'];
                $con['Scale.grade_id'] = $this->data['EmployeeDetail']['grade_id'];
                $con['Scale.step_id'] = $this->data['EmployeeDetail']['step_id'];
                $this->loadModel('Scale');
                $salary = $this->Scale->find('all', array('conditions' => $con));
                //print_r($salary[0]['Scale']['salary']);
                $this->data['EmployeeDetail']['salary'] = $salary[0]['Scale']['salary'];

                $this->loadModel('EmployeeDetail');

                $position = $this->EmployeeDetail->Position->find('first', array('conditions' => array('Position.name' => $this->data['EmployeeDetail']['position_id'])));
                $this->data['EmployeeDetail']['position_id'] = $position['Position']['id'];

                $this->EmployeeDetail->create();
                $this->EmployeeDetail->save($this->data);
                //Give Employee ESS Permission
                $this->loadModel('Group');
                $this->Group->create();
                $this->data['Group']['User']['group_id'] = 25;
                $this->data['Group']['User']['user_id'] = $this->data['Employee']['user_id'];
                $this->Group->User->save($this->data);
                //print_r($this->data);
                $tel = $this->data['Employee']['telephone'];
                $text = "Hello " . $this->data['Person']['first_name'] . ", Your EthioHR account is   U:" . $this->data['User']['username'] . " P:123456  Go to http://www.ethiohr.com.et/web-portal to login. Thanks.";
                $this->data['TextMessage']['name'] = $tel;
                $this->data['TextMessage']['text'] = $text;
                $this->loadModel('TextMessage');
                $this->TextMessage->create();
                $this->TextMessage->save($this->data);

                if ($this->data['User']['email'] !== '') {
                    $this->data['Email']['name'] = "Your EthioHR System Account";
                    $this->data['Email']['to'] = $this->data['User']['email'];
                    $this->data['Email']['from'] = 'ethi_hr@ethiohr.com.et';
                    $this->data['Email']['from_name'] = 'EthioHR';
                    $fullname = $this->data['Person']['first_name'] . ' ' . $this->data['Person']['middle_name'];
                    //echo $body;
                    $body = '<table width="502" border="0">
  <tr>
    <td width="492" height="46" align="right" bgcolor="#0066FF" color="#fff"><div align="center" style="color:#fff"><span>Welcome to EthioHR System</span></div></td>
  </tr>
  <tr>
    <td  style="font-family: Arial,Helvetica,sans-serif;font-size: 14px;"><p>To:  ' . $fullname . '</p>      <p class="style7">&nbsp;&nbsp;&nbsp;Your EthioHR System Account is:<br />
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User Name: <strong>' . $this->data['User']['username'] . '</strong><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Password: <strong>123456</strong><br />
        <br />
&nbsp;
&nbsp;&nbsp;Use the address <strong>http://www.ethio_hr.com.et/web-portal</strong> to access your account and Please change your password after first login!<br />
        <br />
&nbsp;&nbsp;Regards,<br />
&nbsp;&nbsp;EthioHR</p><hr></td>
  </tr>
  <tr>
    <td><span style="color:#999;font-size: 12px;">* Note: Please don\'t reply to this address, it is generated by the system.</span></td>
  </tr>
</table>';
                    $this->data['Email']['body'] = $body;
                    $this->loadModel('Email');
                    $this->Email->create();
                    $this->Email->save($this->data);
                }
                $this->Session->setFlash(__('The employee has been saved', true), '');
                $this->render('/elements/success');
            } else {
                $this->Session->setFlash(__('The employee could not be saved. Please, try again.', true), '');
                $this->render('/elements/failure');
            }
        }
        if ($id)
            $this->set('parent_id', $id);
        //$locations = $this->Employee->Location->find('list');
        $locations = $this->Employee->EmpLoc->generatetreelist(null, null, null, '---');
        $branches = $this->Employee->User->Branch->find('list');
        $users = $this->Employee->User->find('list');
        $this->loadModel('EmployeeDetail');
        $grades = $this->EmployeeDetail->Grade->find('list');
        $steps = $this->EmployeeDetail->Step->find('list');
        $positions = $this->EmployeeDetail->Position->find('list');
        $this->set(compact('locations', 'users', 'branches', 'grades', 'steps', 'positions'));
    }

    function edit($id = null, $parent_id = null) {
        if (!$id && empty($this->data)) {
            $this->Session->setFlash(__('Invalid employee', true), '');
            $this->redirect(array('action' => 'index'));
        }
        /*  if (!empty($this->data)) {
          $this->autoRender = false;
          if ($this->Employee->save($this->data)) {
          $this->Session->setFlash(__('The employee has been saved', true), '');
          $this->render('/elements/success');
          } else {
          $this->Session->setFlash(__('The employee could not be saved. Please, try again.', true), '');
          $this->render('/elements/failure');
          }
          } */


        if (!empty($this->data)) {
            $this->data['Person']['first_name'] = Sanitize::paranoid($this->data['Person']['first_name']);
            $this->data['Person']['middle_name'] = Sanitize::paranoid($this->data['Person']['middle_name']);
            $this->data['Person']['last_name'] = Sanitize::paranoid($this->data['Person']['last_name']);

            $this->autoRender = false;

            if ($this->data['Employee']['photo']['name'] !== '') {
                $this->data['Employee']['photox'] = $this->data['Employee']['photo'];
                $photox = $this->data['Employee']['photo'];
                $this->data['Employee']['photo'] = $this->data['Employee']['photo']["name"];
            } else {
                unset($this->data['Employee']['photo']);
            }
            $this->data = Sanitize::clean($this->data);
            $this->layout = 'message_layout';
            if ($this->Employee->save($this->data)) {
                App::import('Amharic');
                $this->data['Person']['first_name_am'] = Amharic::encode_amharic($this->data['Person']['first_name_am']);
                $this->data['Person']['middle_name_am'] = Amharic::encode_amharic($this->data['Person']['middle_name_am']);
                $this->data['Person']['last_name_am'] = Amharic::encode_amharic($this->data['Person']['last_name_am']);
                // $this->Employee->User->Person->create();
                $this->Employee->User->Person->save($this->data);
                /// $this->data['User']['person_id'] = $this->Employee->User->Person->getLastInsertId();
                //  $this->data['User']['username'] = $this->data['Person']['first_name'] . $this->data['User']['person_id'];
                // $pwd = rand(2000, 9000);
                //  $this->data['User']['password'] = $this->Auth->password($pwd);
                ///  $this->data['User']['is_active'] = 1;
                // $this->Employee->User->create();
                $this->Employee->User->save($this->data);

                if (isset($photox)) {
                    $allowedExts = array("jpg", "jpeg", "gif", "png");
                    $extension = end(explode(".", $photox["name"]));
                    if ((($photox["type"] == "image/gif")
                            || ($photox["type"] == "image/jpeg")
                            || ($photox["type"] == "image/png")
                            || ($photox["type"] == "image/pjpeg"))
                            && in_array($extension, $allowedExts)) {
                        if ($photox["error"] > 0) {
                            
                        } else {
                            if (!is_dir(IMAGES . "employee_photos"))
                                mkdir(IMAGES . "employee_photos", 0777);
                            $photox['name'] = $this->data['Employee']['id'] . "." . $extension;
                            move_uploaded_file($photox['tmp_name'], IMAGES . "employee_photos" . DS . $photox['name']);
                            $this->data['Employee']['photo'] = $photox['name'];
                            $file_name = $photox['name'];
                            $ext = substr($file_name, strripos($file_name, '.') + 1);

                            if (in_array($ext, array('png', 'jpg', 'jpeg', 'gif'))) {
                                list($w1, $h1) = getimagesize(IMAGES . "employee_photos" . DS . $file_name);
                                if ($w1 > 150) {
                                    // Load
                                    $w2 = 150;
                                    $h2 = ($w2 * $h1) / $w1;
                                    if ($h2 > 190)
                                        $h2 = 190;

                                    $thumb = imagecreatetruecolor($w2, $h2);
                                    $source = null;
                                    if (in_array($ext, array('jpg', 'jpeg')))
                                        $source = imagecreatefromjpeg(IMAGES . 'employee_photos' . DS . $file_name);
                                    elseif (in_array($ext, array('png')))
                                        $source = imagecreatefrompng(IMAGES . 'employee_photos' . DS . $file_name);
                                    else
                                        $source = imagecreatefromgif(IMAGES . 'employee_photos' . DS . $file_name);
                                    // Resize
                                    imagecopyresized($thumb, $source, 0, 0, 0, 0, $w2, $h2, $w1, $h1);
                                    //$new_image = 'acuity_' . date('YmdHi') . '.png';
                                    if (in_array($ext, array('jpg', 'jpeg')))
                                        imagejpeg($thumb, IMAGES . 'employee_photos' . DS . $file_name);
                                    elseif (in_array($ext, array('png')))
                                        imagepng($thumb, IMAGES . 'employee_photos' . DS . $file_name);
                                    else
                                        imagegif($thumb, IMAGES . 'employee_photos' . DS . $file_name);

                                    //unlink(IMAGES . 'employee_photos' . DS . $file_name);
                                }
                            }
                        }
                    }
                }
                //$this->data['EmployeeDetail']['employee_id'] = $this->Employee->getLastInsertId();
                // $this->data['Employee']['user_id'] = $this->Employee->User->getLastInsertId();
                $this->Employee->save($this->data);
                $this->data['EmployeeDetail']['start_date'] = $this->data['Employee']['date_of_employment'];
                $this->data['EmployeeDetail']['branch_id'] = $this->data['User']['branch_id'];
                $con['Scale.grade_id'] = $this->data['EmployeeDetail']['grade_id'];
                $con['Scale.step_id'] = $this->data['EmployeeDetail']['step_id'];
                $this->loadModel('Scale');
                $salary = $this->Scale->find('all', array('conditions' => $con));
                //print_r($salary[0]['Scale']['salary']);
                $this->data['EmployeeDetail']['salary'] = $salary[0]['Scale']['salary'];

                $this->loadModel('EmployeeDetail');

                $position = $this->EmployeeDetail->Position->find('first', array('conditions' => array('Position.name' => $this->data['EmployeeDetail']['position_id'])));
                $this->data['EmployeeDetail']['position_id'] = $position['Position']['id'];

                //$this->EmployeeDetail->create();
                $this->EmployeeDetail->save($this->data);
                //print_r($this->data);

                $this->Session->setFlash(__('The employee has been saved', true), '');
                $this->render('/elements/success');
            } else {
                $this->Session->setFlash(__('The employee could not be saved. Please, try again.', true), '');
                $this->render('/elements/failure');
            }
        }
        $this->Employee->recursive = 2;
        $this->set('employee', $this->Employee->read(null, $id));

        if ($parent_id) {
            $this->set('parent_id', $parent_id);
        }

        $locations = $this->Employee->EmpLoc->generatetreelist(null, null, null, '---');
        $branches = $this->Employee->User->Branch->find('list');
        // $users = $this->Employee->User->find('list');
        $this->loadModel('EmployeeDetail');
        $grades = $this->EmployeeDetail->Grade->find('list');
        $steps = $this->EmployeeDetail->Step->find('list');
        $positions = $this->EmployeeDetail->Position->find('list');
        $this->set(compact('locations', 'branches', 'grades', 'steps', 'positions'));
    }

    function deleteh($id = null) {
        $this->autoRender = false;
        if (!$id) {
            $this->Session->setFlash(__('Invalid id for employee', true), '');
            $this->render('/elements/failure');
        }
        $this->data['Employee']['id'] = $id;
        $this->data['Employee']['status'] = 'deleted';
        $this->Employee->save($this->data);
    }

    function delete($id = null) {
        $this->autoRender = false;
        if (!$id) {
            $this->Session->setFlash(__('Invalid id for employee', true), '');
            $this->render('/elements/failure');
        }
        if (stripos($id, '_') !== false) {
            $ids = explode('_', $id);
            try {
                foreach ($ids as $i) {
                    $this->Employee->delete($i);
                }
                $this->Session->setFlash(__('Employee deleted', true), '');
                $this->render('/elements/success');
            } catch (Exception $e) {
                $this->Session->setFlash(__('Employee was not deleted', true), '');
                $this->render('/elements/failure');
            }
        } else {
            if ($this->Employee->delete($id)) {
                $this->Session->setFlash(__('Employee deleted', true), '');
                $this->render('/elements/success');
            } else {
                $this->Session->setFlash(__('Employee was not deleted', true), '');
                $this->render('/elements/failure');
            }
        }
    }

    /**
     * Converts European date to its equivalent Ethiopic Calendar date 
     * 
     * @param String $gdt eg. '2014-04-03' (April 3, 2014)
     * @return String
     */
    private function convertGToE($gdt) {
        $starts = array(26, 21, 22, 22, 23, 24, 22, 23, 23, 24, 24, 25);
        $parts = explode("-", $gdt);
        $gy = $parts[0];
        $gm = $parts[1];
        $gd = $parts[2];

        $ey = ($gm <= 9) ? $gy - 8 : $gy - 7;

        if ($ey % 4 == 0)
            for ($i = 1; $i < 6; $i++)
                $starts[i]--;
        $em = ($gm + 2) % 12 + 1;
        $ed = $starts[($gm + 3) % 12] - (($ey % 4 == 0 && $gm < 9 || ($ey + 1) % 4 == 0 && $gm == 9) ? 1 : 0); // TODO: after - is addition on 20-Sep-2011
        $this->addDays($gd - 1, $ey, $em, $ed);

        $months = array(1 => 'መስከረም', 'ጥቅምት', 'ህዳር', 'ታህሳስ', 'ጥር', 'የካቲት', 'መጋቢት', 'ሚያዝያ', 'ግንቦት', 'ሰኔ', 'ሐምሌ', 'ነሀሴ', 'ጳጉሜን');
        $days = array(1 => 'ሰኞ', 'ማክሰኞ', 'ረቡዕ', 'ሐሙስ', 'ዓርብ', 'ቅዳሜ', 'እሁድ');
        //return $ey . "-" . ($em > 9 ? $em : "0" . $em) . "-" . ($ed > 9 ? $ed : "0" . $ed);
        return  $days[date('N', strtotime($gdt))] . " " . $months[$em] . " " . $ed . "፣ " . $ey . " ዓ. ም";
    }

    private function addDays($diff, &$ey, &$em, &$ed) {
        if ($em < 12) {
            $ed += $diff;
            if ($ed > 30) {
                $em++;
                $ed = $ed - 30;
            }
        } else {
            $ed += $diff;
            if ($ed > 30) {
                $excess = $ed - 30;
                if ($excess > 5) {
                    $excess -= (($ey + 1) % 4 == 0) ? 5 : 6;
                    if ($excess > 0) {
                        $em = 1;
                        $ed = $excess;
                        $ey++;
                    } else {
                        $ed = (($ey + 1) % 4 == 0) ? 6 : 5;
                        $em = 13;
                    }
                }
            }
        }
    }
    
    function ConvertEthiopicToGregoreanDate($ey, $em, $ed){
        $starts = array(11, 11, 10, 10, 9, 8, 10, 9, 9, 8, 8, 7, 6);
        if(($ey + 1) % 4 == 0)
            for ($i = 0; $i < 6; $i++)
                $starts[$i]++;

        $gy = ($em <= 4) ? $ey + 7 : $ey + 8;

        $gm = ($em + 7)%12 + 1;

        $gdt = $gy . $gm . $starts[$em-1];
        $gdt = date('Y-m-d' , strtotime($gdt . ' +' . ($ed - 1) . ' days'));

        return $gdt;
    }
}

?>