-- phpMyAdmin SQL Dump
-- version 3.5.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 05, 2016 at 08:29 PM
-- Server version: 5.5.24-log
-- PHP Version: 5.3.13

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `rf_school_erp`
--

-- --------------------------------------------------------

--
-- Table structure for table `acct_accounts`
--

CREATE TABLE IF NOT EXISTS `acct_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT NULL,
  `name` varchar(200) NOT NULL COMMENT 'account description',
  `code` varchar(50) NOT NULL,
  `acct_category_id` int(11) NOT NULL,
  `balance` decimal(18,2) NOT NULL,
  `user_id` int(11) NOT NULL,
  `lft` int(11) NOT NULL,
  `rght` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `acct_categories`
--

CREATE TABLE IF NOT EXISTS `acct_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT NULL,
  `name` varchar(50) NOT NULL,
  `normal_side` varchar(2) NOT NULL,
  `prefix` varchar(20) NOT NULL,
  `code` varchar(50) NOT NULL,
  `postfix` varchar(20) NOT NULL,
  `last_code` varchar(50) NOT NULL,
  `lft` int(11) NOT NULL,
  `rght` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `acct_fiscal_years`
--

CREATE TABLE IF NOT EXISTS `acct_fiscal_years` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `acct_journals`
--

CREATE TABLE IF NOT EXISTS `acct_journals` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `acct_transaction_id` int(11) NOT NULL,
  `acct_account_id` int(11) NOT NULL,
  `dr` decimal(18,2) NOT NULL,
  `cr` decimal(18,2) NOT NULL,
  `bbf` decimal(18,2) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `acct_transactions`
--

CREATE TABLE IF NOT EXISTS `acct_transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL COMMENT 'reference number - auto generated by controller',
  `description` text NOT NULL,
  `cheque_number` varchar(20) NOT NULL,
  `invoice_number` varchar(20) NOT NULL,
  `transaction_date` date NOT NULL,
  `acct_fiscal_year_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `audit_trails`
--

CREATE TABLE IF NOT EXISTS `audit_trails` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `is_successful` tinyint(1) NOT NULL DEFAULT '0',
  `user_id` int(11) DEFAULT NULL,
  `session_name` varchar(50) DEFAULT NULL,
  `action_made` varchar(5) DEFAULT NULL,
  `table_name` varchar(50) DEFAULT NULL,
  `old_value` text,
  `new_value` text,
  `record_id` int(11) DEFAULT NULL,
  `audit_desc` varchar(255) DEFAULT '',
  `created` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `checksums`
--

CREATE TABLE IF NOT EXISTS `checksums` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `rid` int(11) NOT NULL,
  `cvalue` varchar(100) NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `containers`
--

CREATE TABLE IF NOT EXISTS `containers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `category` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `list_order` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `countries`
--

CREATE TABLE IF NOT EXISTS `countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `code` varchar(50) NOT NULL,
  `currency` varchar(100) NOT NULL,
  `nationality` varchar(100) NOT NULL,
  `language` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_absentees`
--

CREATE TABLE IF NOT EXISTS `edu_absentees` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_attendance_record_id` int(11) NOT NULL,
  `edu_student_id` int(11) NOT NULL,
  `code` varchar(500) NOT NULL,
  `reason` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_academic_years`
--

CREATE TABLE IF NOT EXISTS `edu_academic_years` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `status_id` int(11) NOT NULL COMMENT 'AC-Active, CL-Closed',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_assessments`
--

CREATE TABLE IF NOT EXISTS `edu_assessments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_assessment_type_id` int(11) NOT NULL,
  `edu_teacher_id` int(11) NOT NULL,
  `edu_section_id` int(11) NOT NULL,
  `max_value` int(11) NOT NULL,
  `date` date NOT NULL,
  `status` varchar(100) NOT NULL DEFAULT 'active',
  `detail` varchar(500) NOT NULL,
  `edu_course_id` int(11) NOT NULL,
  `edu_quarter_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_assessment_records`
--

CREATE TABLE IF NOT EXISTS `edu_assessment_records` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_student_id` int(11) NOT NULL,
  `edu_assessment_id` int(11) NOT NULL,
  `mark` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_assessment_types`
--

CREATE TABLE IF NOT EXISTS `edu_assessment_types` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_assignments`
--

CREATE TABLE IF NOT EXISTS `edu_assignments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_teacher_id` int(11) NOT NULL,
  `edu_course_id` int(11) NOT NULL,
  `edu_section_id` int(11) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_attendance_records`
--

CREATE TABLE IF NOT EXISTS `edu_attendance_records` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_teacher_id` int(11) NOT NULL,
  `edu_section_id` int(11) NOT NULL,
  `edu_quarter_id` int(11) NOT NULL,
  `date` date NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_calendar_events`
--

CREATE TABLE IF NOT EXISTS `edu_calendar_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `edu_calendar_event_type_id` int(11) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `edu_quarter_id` int(11) NOT NULL,
  `edu_campus_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_calendar_event_types`
--

CREATE TABLE IF NOT EXISTS `edu_calendar_event_types` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `educational` tinyint(1) NOT NULL,
  `applicable` varchar(1) NOT NULL DEFAULT 'E' COMMENT 'E - Educational, N - Non-Educational, B - Both',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_campuses`
--

CREATE TABLE IF NOT EXISTS `edu_campuses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `address` varchar(200) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COMMENT='ERR-101XX' AUTO_INCREMENT=2 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_classes`
--

CREATE TABLE IF NOT EXISTS `edu_classes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `cvalue` int(11) NOT NULL,
  `min_for_promotion` decimal(18,2) NOT NULL,
  `edu_class_level_id` int(11) NOT NULL COMMENT '1 = for Lower, 2 = Primary, 3 = Mid-Level, 4 = High ',
  `uni_teacher` tinyint(1) NOT NULL COMMENT 'True = Managed by a single teacher, False = Otherwise',
  `grading_type` varchar(1) NOT NULL COMMENT 'A = Alphabetic, N = Numeric, G = Guideline, M = Mixed',
  `enrollment_fee` decimal(18,2) NOT NULL,
  `registration_fee` decimal(18,2) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_class_levels`
--

CREATE TABLE IF NOT EXISTS `edu_class_levels` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `remark` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_courses`
--

CREATE TABLE IF NOT EXISTS `edu_courses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_class_id` int(11) NOT NULL,
  `edu_subject_id` int(11) NOT NULL,
  `description` text NOT NULL,
  `min_for_pass` decimal(18,2) NOT NULL,
  `is_mandatory` tinyint(1) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_days`
--

CREATE TABLE IF NOT EXISTS `edu_days` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `week_day` int(11) NOT NULL,
  `edu_quarter_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_evaluations`
--

CREATE TABLE IF NOT EXISTS `edu_evaluations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_class_id` int(11) NOT NULL,
  `edu_evaluation_area_id` int(11) NOT NULL,
  `order_level` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_evaluation_areas`
--

CREATE TABLE IF NOT EXISTS `edu_evaluation_areas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `edu_evaluation_category_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_evaluation_categories`
--

CREATE TABLE IF NOT EXISTS `edu_evaluation_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `list_order` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `list_order` (`list_order`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_event_tasks`
--

CREATE TABLE IF NOT EXISTS `edu_event_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_calendar_event_type_id` int(11) NOT NULL,
  `task` varchar(100) NOT NULL,
  `permissions` varchar(100) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_experiences`
--

CREATE TABLE IF NOT EXISTS `edu_experiences` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_teacher_id` int(11) NOT NULL,
  `organization` varchar(100) NOT NULL,
  `title` varchar(100) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_extra_payments`
--

CREATE TABLE IF NOT EXISTS `edu_extra_payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_extra_payment_setting_id` int(11) NOT NULL,
  `edu_student_id` int(11) NOT NULL,
  `is_paid` tinyint(1) NOT NULL,
  `date_paid` date NOT NULL,
  `paid_amount` decimal(18,2) NOT NULL,
  `cheque_number` varchar(50) NOT NULL,
  `cheque_amount` decimal(18,2) NOT NULL,
  `invoice` varchar(50) NOT NULL,
  `transaction_ref` varchar(50) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_extra_payment_settings`
--

CREATE TABLE IF NOT EXISTS `edu_extra_payment_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `edu_class_id` int(11) NOT NULL,
  `amount` decimal(18,2) NOT NULL,
  `edu_academic_year_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_grade_rules`
--

CREATE TABLE IF NOT EXISTS `edu_grade_rules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(500) NOT NULL,
  `type` varchar(500) NOT NULL,
  `created_date` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_grade_rule_values`
--

CREATE TABLE IF NOT EXISTS `edu_grade_rule_values` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `min` int(11) NOT NULL,
  `max` int(11) NOT NULL,
  `code` varchar(500) NOT NULL,
  `edu_grade_rule_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_guidelines`
--

CREATE TABLE IF NOT EXISTS `edu_guidelines` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(10) NOT NULL,
  `description` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_homerooms`
--

CREATE TABLE IF NOT EXISTS `edu_homerooms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_section_id` int(11) NOT NULL,
  `edu_teacher_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_lesson_plans`
--

CREATE TABLE IF NOT EXISTS `edu_lesson_plans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_course_id` int(11) NOT NULL,
  `edu_section_id` int(11) NOT NULL,
  `maker_id` int(11) NOT NULL,
  `checker_id` int(11) NOT NULL,
  `is_posted` tinyint(1) NOT NULL,
  `posts` int(11) NOT NULL,
  `status` varchar(20) NOT NULL COMMENT 'Created, Posted, Approved, Rejected, Returned',
  `reason` varchar(255) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_lesson_plan_items`
--

CREATE TABLE IF NOT EXISTS `edu_lesson_plan_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_lesson_plan_id` int(11) NOT NULL,
  `edu_period_id` int(11) NOT NULL,
  `edu_day_id` int(11) NOT NULL,
  `edu_outline_id` int(11) NOT NULL,
  `activity` varchar(1000) NOT NULL,
  `materials_needed` varchar(1000) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_nonavailable_periods`
--

CREATE TABLE IF NOT EXISTS `edu_nonavailable_periods` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_teacher_id` int(11) NOT NULL,
  `edu_schedule_id` int(11) NOT NULL,
  `day` varchar(100) NOT NULL,
  `period` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_outlines`
--

CREATE TABLE IF NOT EXISTS `edu_outlines` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(800) NOT NULL,
  `edu_course_id` int(11) NOT NULL,
  `list_order` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_parents`
--

CREATE TABLE IF NOT EXISTS `edu_parents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `authorized_person` varchar(100) NOT NULL COMMENT 'authorized person(s) to take student from school',
  `marital_status` varchar(50) NOT NULL,
  `primary_parent` varchar(2) NOT NULL COMMENT 'M - Mother, F - Father, G - Guardian',
  `user_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_parent_details`
--

CREATE TABLE IF NOT EXISTS `edu_parent_details` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(100) NOT NULL,
  `middle_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `residence_address` varchar(200) NOT NULL,
  `nationality` varchar(50) NOT NULL,
  `relationship` varchar(50) NOT NULL,
  `occupation` varchar(100) NOT NULL,
  `academic_qualification` varchar(50) NOT NULL,
  `employment_status` varchar(2) NOT NULL COMMENT 'E - employed, N - Not-employed, NA - Not Applicable, S - Self Employed',
  `employer` varchar(100) NOT NULL,
  `work_address` varchar(200) NOT NULL,
  `work_telephone` varchar(50) NOT NULL,
  `mobile` varchar(15) NOT NULL,
  `email` varchar(255) NOT NULL,
  `photo_file` varchar(25) NOT NULL,
  `family_type` varchar(2) NOT NULL COMMENT 'F - Father, M - Mother, G - Guardian',
  `edu_parent_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_payments`
--

CREATE TABLE IF NOT EXISTS `edu_payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_payment_schedule_id` int(11) NOT NULL,
  `edu_student_id` int(11) NOT NULL,
  `is_paid` tinyint(1) NOT NULL,
  `date_paid` date NOT NULL,
  `paid_amount` decimal(18,2) NOT NULL,
  `cheque_number` varchar(50) NOT NULL,
  `cheque_amount` decimal(18,2) NOT NULL,
  `invoice` varchar(50) NOT NULL,
  `transaction_ref` varchar(50) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_payment_schedules`
--

CREATE TABLE IF NOT EXISTS `edu_payment_schedules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `month` int(100) NOT NULL,
  `edu_class_id` int(11) NOT NULL,
  `amount` decimal(18,2) NOT NULL,
  `edu_academic_year_id` int(11) NOT NULL,
  `due_date` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_periods`
--

CREATE TABLE IF NOT EXISTS `edu_periods` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_section_id` int(11) NOT NULL,
  `edu_course_id` int(11) NOT NULL,
  `edu_schedule_id` int(11) NOT NULL,
  `edu_teacher_id` int(11) NOT NULL DEFAULT '0',
  `day` varchar(100) NOT NULL,
  `period` varchar(100) NOT NULL,
  `actor` varchar(100) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_quarters`
--

CREATE TABLE IF NOT EXISTS `edu_quarters` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `short_name` varchar(5) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `edu_academic_year_id` int(11) NOT NULL,
  `quarter_type` varchar(1) NOT NULL DEFAULT 'E' COMMENT 'E - Educational, N - Non-Educational',
  `status` varchar(2) NOT NULL COMMENT 'CR-Created, AC-Active or Open, CL-Closed',
  `user_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_receipts`
--

CREATE TABLE IF NOT EXISTS `edu_receipts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(1000) NOT NULL,
  `reference_number` varchar(6) NOT NULL,
  `invoice_date` date NOT NULL,
  `crm_number` varchar(50) NOT NULL,
  `parent_name` varchar(100) NOT NULL,
  `parent_address` varchar(200) NOT NULL,
  `edu_student_id` int(11) NOT NULL,
  `student_name` varchar(100) NOT NULL,
  `student_number` varchar(50) NOT NULL,
  `student_class` varchar(100) NOT NULL,
  `student_section` varchar(100) NOT NULL,
  `student_academic_year` varchar(100) NOT NULL,
  `total_before_tax` decimal(18,2) NOT NULL,
  `total_after_tax` decimal(18,2) NOT NULL,
  `VAT` decimal(18,2) NOT NULL,
  `TOT` decimal(18,2) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_receipt_items`
--

CREATE TABLE IF NOT EXISTS `edu_receipt_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `amount` decimal(18,2) NOT NULL,
  `edu_receipt_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_registrations`
--

CREATE TABLE IF NOT EXISTS `edu_registrations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `edu_student_id` int(11) NOT NULL,
  `edu_class_id` int(11) NOT NULL,
  `edu_section_id` int(11) NOT NULL,
  `edu_campus_id` int(11) NOT NULL,
  `grand_total_average` decimal(18,2) NOT NULL DEFAULT '0.00',
  `rank` int(11) NOT NULL DEFAULT '0',
  `status` varchar(1) NOT NULL DEFAULT 'A' COMMENT 'P - Promoted, N - Not promoted, A - Active, I - Inactive, U -Unregistered',
  `failure_count` int(11) NOT NULL DEFAULT '0' COMMENT 'Holds the number of not-promoted registrations of a student',
  `allowed` varchar(1) NOT NULL DEFAULT 'A' COMMENT 'A-Allowed for next registartion, N-Not allowed',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_registration_evaluations`
--

CREATE TABLE IF NOT EXISTS `edu_registration_evaluations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_registration_id` int(11) NOT NULL,
  `edu_evaluation_id` int(11) NOT NULL,
  `edu_quarter_id` int(11) NOT NULL,
  `edu_guideline_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_registration_quarters`
--

CREATE TABLE IF NOT EXISTS `edu_registration_quarters` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_registration_id` int(11) NOT NULL,
  `edu_quarter_id` int(11) NOT NULL,
  `quarter_average` decimal(18,2) NOT NULL DEFAULT '0.00',
  `quarter_rank` int(11) NOT NULL,
  `class_rank` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_registration_quarter_results`
--

CREATE TABLE IF NOT EXISTS `edu_registration_quarter_results` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_registration_quarter_id` int(11) NOT NULL,
  `edu_course_id` int(11) NOT NULL,
  `course_result` decimal(18,2) NOT NULL,
  `course_rank` int(11) NOT NULL,
  `result_indicator` varchar(1) NOT NULL DEFAULT 'N' COMMENT 'P - Pass, F - Fail, N - Not set',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_required_documents`
--

CREATE TABLE IF NOT EXISTS `edu_required_documents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `edu_registration_id` int(11) NOT NULL,
  `presented` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_results`
--

CREATE TABLE IF NOT EXISTS `edu_results` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_registration_id` int(11) NOT NULL,
  `edu_assessment_id` int(11) NOT NULL,
  `result` double NOT NULL,
  `bonus` double NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_schedules`
--

CREATE TABLE IF NOT EXISTS `edu_schedules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(500) NOT NULL,
  `periods` int(11) NOT NULL,
  `days` int(11) NOT NULL,
  `status` varchar(100) NOT NULL DEFAULT 'not_default',
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_sections`
--

CREATE TABLE IF NOT EXISTS `edu_sections` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `edu_campus_id` int(11) NOT NULL,
  `edu_class_id` int(11) NOT NULL,
  `edu_academic_year_id` int(11) NOT NULL,
  `edu_teacher_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_siblings`
--

CREATE TABLE IF NOT EXISTS `edu_siblings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `age` int(11) NOT NULL,
  `grade` varchar(20) NOT NULL,
  `sex` varchar(2) NOT NULL,
  `edu_student_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_students`
--

CREATE TABLE IF NOT EXISTS `edu_students` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `identity_number` varchar(100) NOT NULL,
  `birth_date` date NOT NULL,
  `registration_date` date NOT NULL,
  `gender` varchar(2) NOT NULL COMMENT 'F-Female, M-Male',
  `nationality` varchar(50) NOT NULL,
  `edu_parent_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `photo_file_name` varchar(50) NOT NULL,
  `maker_id` int(11) NOT NULL,
  `status` int(11) NOT NULL COMMENT '1 = Active, 2 = Inactive, 3 = Dismissed, 4 = Withdrawn, 5 = Transferred, 6 = Incomplete,  7 = Unregistered but Enrolled, 8 = Unknown',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_student_conditions`
--

CREATE TABLE IF NOT EXISTS `edu_student_conditions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_student_id` int(11) NOT NULL,
  `learning_condition` varchar(100) NOT NULL,
  `health_condition` varchar(50) NOT NULL,
  `treatment_type` varchar(200) NOT NULL,
  `health_care_institute` varchar(100) NOT NULL,
  `physician` varchar(100) NOT NULL,
  `alergy` varchar(200) NOT NULL,
  `physical_condition` varchar(200) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_subjects`
--

CREATE TABLE IF NOT EXISTS `edu_subjects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `min_for_pass` decimal(18,2) NOT NULL,
  `is_mandatory` tinyint(1) NOT NULL,
  `color` varchar(50) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_subjects_teachers`
--

CREATE TABLE IF NOT EXISTS `edu_subjects_teachers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_subject_id` int(11) NOT NULL,
  `edu_teacher_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_subscriptions`
--

CREATE TABLE IF NOT EXISTS `edu_subscriptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `edu_parent_id` int(11) NOT NULL,
  `sms` tinyint(1) NOT NULL,
  `email` tinyint(1) NOT NULL,
  `portal` tinyint(1) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_teachers`
--

CREATE TABLE IF NOT EXISTS `edu_teachers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identity_number` varchar(50) NOT NULL,
  `date_of_employment` date NOT NULL,
  `user_id` int(11) NOT NULL,
  `city` varchar(50) NOT NULL,
  `sub_city` varchar(50) NOT NULL,
  `woreda` varchar(50) NOT NULL,
  `house_number` varchar(20) NOT NULL,
  `telephone_home` varchar(50) NOT NULL,
  `telephone_mobile` varchar(50) NOT NULL,
  `edu_class_level_id` int(11) NOT NULL,
  `photo` varchar(20) NOT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `edu_teacher_allocations`
--

CREATE TABLE IF NOT EXISTS `edu_teacher_allocations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `edu_teacher_id` int(11) NOT NULL,
  `edu_course_id` int(11) NOT NULL,
  `edu_section_id` int(11) NOT NULL,
  `weekly` int(11) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `groups`
--

CREATE TABLE IF NOT EXISTS `groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `is_builtin` tinyint(1) NOT NULL DEFAULT '0',
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `groups_permissions`
--

CREATE TABLE IF NOT EXISTS `groups_permissions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  `permission_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `groups_users`
--

CREATE TABLE IF NOT EXISTS `groups_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `help_contents`
--

CREATE TABLE IF NOT EXISTS `help_contents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `code` varchar(20) NOT NULL,
  `content` text NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `help_items`
--

CREATE TABLE IF NOT EXISTS `help_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `content` text NOT NULL,
  `list_order` int(11) NOT NULL,
  `lft` int(11) NOT NULL,
  `rght` int(11) NOT NULL,
  `version` varchar(20) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `holidays`
--

CREATE TABLE IF NOT EXISTS `holidays` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `date` date NOT NULL,
  `is_recurrent` tinyint(1) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `links`
--

CREATE TABLE IF NOT EXISTS `links` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) CHARACTER SET utf8 NOT NULL,
  `container_id` int(11) NOT NULL,
  `controller` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `action` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `parameter` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT ' ',
  `function_name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `list_order` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `logs`
--

CREATE TABLE IF NOT EXISTS `logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` text NOT NULL,
  `tag` varchar(50) NOT NULL,
  `log_type` varchar(10) NOT NULL,
  `user_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `people`
--

CREATE TABLE IF NOT EXISTS `people` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(100) CHARACTER SET utf8 NOT NULL,
  `middle_name` varchar(100) CHARACTER SET utf8 NOT NULL,
  `last_name` varchar(100) CHARACTER SET utf8 NOT NULL,
  `birthdate` date NOT NULL,
  `birth_location` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `residence_location` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `kebele_or_farmers_association` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `house_number` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `permissions`
--

CREATE TABLE IF NOT EXISTS `permissions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT NULL,
  `name` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(400) COLLATE utf8_unicode_ci NOT NULL,
  `prerequisite` int(11) NOT NULL,
  `lft` int(11) NOT NULL,
  `rght` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `restore_points`
--

CREATE TABLE IF NOT EXISTS `restore_points` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `settings`
--

CREATE TABLE IF NOT EXISTS `settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) CHARACTER SET utf8 NOT NULL,
  `setting_value` varchar(50) CHARACTER SET utf8 NOT NULL,
  `date_from` date NOT NULL,
  `date_to` date NOT NULL,
  `remark` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `statuses`
--

CREATE TABLE IF NOT EXISTS `statuses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `tables` text NOT NULL COMMENT 'comma delimited list of tables that use the status for itself',
  `remark` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `sub_cities`
--

CREATE TABLE IF NOT EXISTS `sub_cities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `tasks`
--

CREATE TABLE IF NOT EXISTS `tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `controller` varchar(100) NOT NULL,
  `action` varchar(100) NOT NULL,
  `iconcls` varchar(100) NOT NULL,
  `function_name` varchar(50) NOT NULL,
  `lft` int(11) NOT NULL,
  `rght` int(11) NOT NULL,
  `list_order` int(11) NOT NULL,
  `built_in` tinyint(1) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `text_messages`
--

CREATE TABLE IF NOT EXISTS `text_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `receiver` varchar(13) NOT NULL,
  `message` text NOT NULL,
  `status` varchar(2) NOT NULL COMMENT 'N-Created but not Sent, S-Sent, F - Tried and Failed',
  `remark` varchar(200) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '0',
  `security_question` varchar(200) CHARACTER SET utf8 NOT NULL DEFAULT 'not specified',
  `security_answer` varchar(200) CHARACTER SET utf8 NOT NULL DEFAULT 'not specified',
  `person_id` int(11) NOT NULL,
  `edu_campus_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`,`email`),
  KEY `FK_users_people` (`person_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

--
-- Constraints for dumped tables
--

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
